# Copyright (C) 2025 Southern California Edison

logging suite "GEISA API - Test discovery messages"
cukinia_log "$(_colorize blue "--- GEISA API - Test discovery messages ---")"

as "Checking discovery geisa messages" cukinia_cmd gapi_discovery geisa
as "Checking discovery device messages" cukinia_cmd gapi_discovery device
as "Checking discovery operator messages" cukinia_cmd gapi_discovery operator
as "Checking discovery metrology messages" cukinia_cmd gapi_discovery metrology
as "Checking discovery sensor messages" cukinia_cmd gapi_discovery sensor
as "Checking discovery network messages" cukinia_cmd gapi_discovery network
as "Checking discovery waveform messages" cukinia_cmd gapi_discovery waveform
