# Copyright (C) 2026 Southern California Edison

logging suite "GEISA API - Test instantaneous messages"
cukinia_log "$(_colorize blue "--- GEISA API - Test instantaneous messages ---")"

as "Checking instantaneous messages" cukinia_cmd gapi_instantaneous
