# Copyright (C) 2026 Southern California Edison

logging suite "GEISA API - Test waveform messages"
cukinia_log "$(_colorize blue "--- GEISA API - Test waveform messages ---")"

test_id "GEISA-API-WAVE-01" \
as "Checking waveform subscription/unsubscription" cukinia_cmd gapi_waveform subscribe_unsubscribe

test_id "GEISA-API-WAVE-02" \
as "Checking waveform already subscribed" cukinia_cmd gapi_waveform already_subscribed
