# Copyright (C) 2026 Southern California Edison

logging suite "GEISA ADM - Conditions before package update"
cukinia_log "$(_colorize blue "--- GEISA ADM - Conditions before package update ---")"

as "Checking if UPDATE_STATE is INITIAL(0) before package update" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/7" \
    --expected-key "content.value" \
    --expected-value "0"

as "Checking if ACTIVATION_STATE is DISABLED(0) before package activation" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/12" \
    --expected-key "content.value" \
    --expected-value "False"