# Copyright (C) 2026 Southern California Edison

logging suite "GEISA ADM - Conditions after package update"
cukinia_log "$(_colorize blue "--- GEISA ADM - Conditions after package update ---")"

as "Checking if package can be pushed to client" \
    cukinia_cmd verbose _py \
    --command "push" \
    --object-uri "9/0/2" \
    --expected-key "success" \
    --expected-value "True" \
    --package-path "${package_path}"

as "Checking if UPDATE_STATE is changed to DELIVERED(3) after package update" \
    cukinia_cmd verbose _py \
    --command "read" \
    --object-uri "9/0/7" \
    --expected-key "content.value" \
    --expected-value "3"

as "Checking if ACTIVATION_STATE is DISABLED(0) before package activation" \
    cukinia_cmd verbose _py \
    --command "read" \
    --object-uri "9/0/12" \
    --expected-key "content.value" \
    --expected-value "False"
