# Copyright (C) 2026 Southern California Edison

logging suite "GEISA ADM - Conditions after package installation"
cukinia_log "$(_colorize blue "--- GEISA ADM - Conditions after package installation ---")"

as "Checking if package can be installed on client" \
    cukinia_cmd _py \
    --command "execute" \
    --object-uri "9/0/4" \
    --expected-key "success" \
    --expected-value "True"

as "Checking if UPDATE_STATE is changed to INSTALLED(4) after package installation" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/7" \
    --expected-key "content.value" \
    --expected-value "4"

as "Checking if ACTIVATION_STATE is DISABLED(0) before package activation" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/12" \
    --expected-key "content.value" \
    --expected-value "False"
