# Copyright (C) 2026 Southern California Edison

logging suite "GEISA ADM - Conditions after package activation"
cukinia_log "$(_colorize blue "--- GEISA ADM - Conditions after package activation ---")"

as "Checking if package can be activated on client" \
    cukinia_cmd _py \
    --command "execute" \
    --object-uri "9/0/10" \
    --expected-key "success" \
    --expected-value "True"

as "Checking if ACTIVATION_STATE is ACTIVATED(1) after package activation" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/12" \
    --expected-key "content.value" \
    --expected-value "True"