# Copyright (C) 2026 Southern California Edison

logging suite "GEISA ADM - Conditions after package deactivation"
cukinia_log "$(_colorize blue "--- GEISA ADM - Conditions after package deactivation ---")"

as "Checking if package can be deactivated on client" \
    cukinia_cmd _py \
    --command "execute" \
    --object-uri "9/0/11" \
    --expected-key "success" \
    --expected-value "True"

as "Checking if ACTIVATION_STATE is DEACTIVATED(0) after package deactivation" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/12" \
    --expected-key "content.value" \
    --expected-value "False"
