# Copyright (C) 2026 Southern California Edison

logging suite "GEISA ADM - Conditions after package uninstallation"
cukinia_log "$(_colorize blue "--- GEISA ADM - Conditions after package uninstallation ---")"

as "Checking if package can be uninstalled on client" \
    cukinia_cmd _py \
    --command "execute" \
    --object-uri "9/0/6" \
    --expected-key "success" \
    --expected-value "true"

as "Checking if UPDATE_STATE is reset to INITIAL(0) after package uninstallation" \
    cukinia_cmd _py \
    --command "read" \
    --object-uri "9/0/7" \
    --expected-key "content.value" \
    --expected-value "0"
