# Copyright (C) 2026 Southern California Edison

if [ -z "${GLEE_TESTS}" ] || echo "${GLEE_TESTS}" | grep -Eq "(^| )operating_system($| )"; then
	logging suite "GEISA LEE - Operating System"
	cukinia_log "$(_colorize blue "--- GEISA LEE - Operating System ---")"

	# ==================================== MUST ====================================

	# =================================== SHALL ====================================

	test_id "GEISA-LEE-OS-01" \
	as "GEISA LEE SHALL use Linux as the core operating system." \
	cukinia_test $(uname | grep -c "Linux") -eq 1

	# =================================== SHOULD ===================================

	KERNEL_VERSION=$(uname -r | cut -d. -f1,2)

	test_id "GEISA-LEE-OS-02" \
	as "The LEE platform implementer SHOULD use a Linux 6.x or greater kernel." \
	cukinia_test $(echo $KERNEL_VERSION | grep -c "^6\.[0-9]\+") -eq 1

	# ==================================== MAY =====================================
fi
