# Copyright (C) 2026 Southern California Edison

if [ -z "${GLEE_TESTS}" ] || echo "${GLEE_TESTS}" | grep -Eq "(^| )app_isolation($| )"; then
	logging suite "GEISA LEE - Application Isolation"
	cukinia_log "$(_colorize blue "--- GEISA LEE - Application Isolation ---")"

	# ==================================== MUST ====================================

	# =================================== SHALL ====================================

	test_id "GEISA-LEE-APP-01" \
	as "GEISA applications SHALL be isolated from each other as described in /system-architecture." \
	cukinia_cmd $GEISA_LEE_TESTS_DIR/tests.d/check-config.sh

	# =================================== SHOULD ===================================

	# ==================================== MAY =====================================
fi
