# Copyright (C) 2026 Southern California Edison

if [ -z "${GLEE_TESTS}" ] || echo "${GLEE_TESTS}" | grep -Eq "(^| )app_isolation($| )"; then
	logging suite "GEISA LEE - Application Isolation"
	cukinia_log "$(_colorize blue "--- GEISA LEE - Application Isolation ---")"

	. "$LEE_TESTS_DIR/tests.d/check-container.sh"

	# ==================================== MUST ====================================

	privileged_test_id "GEISA-LEE-APP-MUST-01" \
	as "The platform MUST provide a base image" \
	cukinia_cmd check_container_image_layer base

	privileged_test_id "GEISA-LEE-APP-MUST-02" \
	as "The platform MUST accept application images" \
	cukinia_cmd check_container_image_layer application

	# =================================== SHALL ====================================

	privileged_test_id "GEISA-LEE-APP-SHALL-03" \
	as "GEISA applications SHALL be isolated from each other as described in /system-architecture." \
	cukinia_cmd check_container_namespaces_are_isolated

	privileged_test_id "GEISA-LEE-APP-SHALL-04" \
	as "The platform SHALL control the number of CPUs allocated to a GEISA application." \
	cukinia_cmd check_all_container_cgroup_constraints cpu-count

	privileged_test_id "GEISA-LEE-APP-SHALL-05" \
	as "The platform SHALL control the percentage of CPU allowed to a GEISA application." \
	cukinia_cmd check_all_container_cgroup_constraints cpu-percent

	privileged_test_id "GEISA-LEE-APP-SHALL-06" \
	as "The platform SHALL control the priority of a GEISA application." \
	cukinia_cmd check_all_container_cgroup_constraints cpu-priority

	privileged_test_id "GEISA-LEE-APP-SHALL-07" \
	as "The platform SHALL control the maximum RAM allocated to a GEISA application." \
	cukinia_cmd check_all_container_cgroup_constraints memory

	privileged_test_id "GEISA-LEE-APP-SHALL-08" \
	as "The platform SHALL control a GEISA application's persistent storage" \
	cukinia_cmd check_container_storage_limit persistent

	privileged_test_id "GEISA-LEE-APP-SHALL-09" \
	as "The platform SHALL control a GEISA application's non-persistent storage" \
	cukinia_cmd check_container_storage_limit nonpersistent

	when "has_container_network_grant" \
	privileged_test_id "GEISA-LEE-APP-SHALL-10" \
	as "The platform SHALL provide standard socket-based IP connectivity when granted in the operator manifest" \
	cukinia_cmd check_container_network_standard_sockets

	when "has_container_network_grant" \
	privileged_test_id "GEISA-LEE-APP-SHALL-11" \
	as "The platform SHALL enforce the network access control list described in the application manifest" \
	cukinia_cmd check_container_network_acl

	when "has_container_network_grant" \
	privileged_test_id "GEISA-LEE-APP-SHALL-12" \
	as "The platform SHALL enforce the network volume limits described in the application manifest" \
	cukinia_cmd check_container_network_volume_limit

	# =================================== SHOULD ===================================

	# ==================================== MAY =====================================
fi
