# Copyright (C) 2026 Southern California Edison

if [ -z "${GLEE_TESTS}" ] || echo "${GLEE_TESTS}" | grep -Eq "(^| )base_libraries($| )"; then
	logging suite "GEISA LEE - Linux Base Libraries"
	cukinia_log "$(_colorize blue "--- GEISA LEE - Linux Base Libraries ---")"

	. "$LEE_TESTS_DIR/tests.d/check-container.sh"

	# From the "Base Libraries" sub-chapter of the GEISA's "Linux Execution Environment" specification
	base_libraries="libasyncns libatomic libcrypto libutil libz libmosquitto libprotobuf"

	# ==================================== MUST ====================================

	test_index=1
	for library in $base_libraries; do
	    privileged_test_id "GEISA-LEE-LIB-MUST-$(printf '%02d' "$test_index")" \
	    as "Other C Libraries (MUST): $library" \
	    cukinia_cmd check_all_containers_have_library "$library"
	    test_index=$((test_index + 1))
	done

	# =================================== SHALL ====================================

	# =================================== SHOULD ===================================

	# ==================================== MAY =====================================
fi
