# Copyright (C) 2026 Southern California Edison

if [ -z "${GLEE_TESTS}" ] || echo "${GLEE_TESTS}" | grep -Eq "(^| )base_libraries($| )"; then
	logging suite "GEISA LEE - Linux Base Libraries"
	cukinia_log "$(_colorize blue "--- GEISA LEE - Linux Base Libraries ---")"

	# ==================================== MUST ====================================

	index=1
	for library in $BASE_LIBRARIES; do
	    test_id "GEISA-LEE-LIB-$(printf '%02d' "$index")" \
	    as "Other C Libraries (MUST): $library" \
	    cukinia_test $(/usr/sbin/ldconfig -p | grep -c "$library") -gt 0
	    index=$((index + 1))
	done

	# =================================== SHALL ====================================

	# =================================== SHOULD ===================================

	# ==================================== MAY =====================================
fi
