# Copyright (C) 2026 Southern California Edison

if [ -z "${GLEE_TESTS}" ] || echo "${GLEE_TESTS}" | grep -Eq "(^| )file_layout($| )"; then
	logging suite "GEISA LEE - Base Filesystem"
	cukinia_log "$(_colorize blue "--- GEISA LEE - Base Filesystem ---")"

	# ==================================== MUST ====================================

	index=1
	for binary in $BASE_BINARIES; do
	    test_id "GEISA-LEE-FS-$(printf '%02d' "$index")" \
	    as "A base set of executables typically found in an embedded or minimal container environment MUST be present ($binary)." \
	    cukinia_test $(which $binary | wc -l) -gt 0
	    index=$((index + 1))
	done

	# =================================== SHALL ====================================

	# =================================== SHOULD ===================================

	# ==================================== MAY =====================================
fi
